#!/bin/sh
# "Russia" list set (B1): the lists that "VPN primary" sends direct by default.
# Standalone on purpose (no common.sh): called from S98singbox-rules at boot, from
# lists-update.sh and from the panel API. The "World" set keeps its own code paths.
#
# Usage: direct-lists.sh {ipsets|dnsmasq|subnets|download|all|destroy}
#   ipsets    create the 8 direct_* ipsets (idempotent)
#   dnsmasq   regenerate /opt/etc/dnsmasq.d/direct-domains*.conf (caller restarts dnsmasq)
#   subnets   reload direct_subnets* from local + remote lists without a gap (ipset swap)
#   download  fetch <lists source>/direct_<file> (next to the World files, which old
#             versions fetch by exact name and never see these); a missing file keeps the previous copy
#   all       ipsets + dnsmasq + subnets
#   destroy   remove the direct_* ipsets (uninstall)

export PATH="/opt/bin:/opt/sbin:/usr/bin:/usr/sbin:/bin:/sbin"

H=/opt/etc/vpn-manager
SETTINGS_FILE="$H/settings.json"
DOM="$H/direct-domains.txt"
DOM_UDP="$H/direct-domains-udp.txt"
SUB="$H/direct-subnets.txt"
SUB_UDP="$H/direct-subnets-udp.txt"
R="$H/remote-lists/direct"
CONF=/opt/etc/dnsmasq.d/direct-domains.conf
CONF_UDP=/opt/etc/dnsmasq.d/direct-domains-udp.conf
DEFAULT_LISTS_SOURCE="https://raw.githubusercontent.com/6g22zdtvk8-tech/split-kvn-lists/main"
REMOTE_FILES="tcp_udp_domains.txt udp_domains.txt tcp_udp_subnets.txt udp_subnets.txt"

log() {
    logger -t direct-lists "$1"
    [ -t 1 ] && echo "$1"
    return 0
}

# Same switch as the World set: remote lists count only while auto-update is on
auto_update_on() {
    [ "$(jq 'if .auto_update_lists == null then true else .auto_update_lists end' "$SETTINGS_FILE" 2>/dev/null)" != "false" ]
}

# Local + remote list, comments and blanks dropped, wildcards stripped, deduplicated
merged() {
    {
        [ -f "$1" ] && cat "$1"
        auto_update_on && [ -f "$2" ] && cat "$2"
    } 2>/dev/null | tr -d ' \t\r' | grep -v '^#' | grep -v '^$' | sed 's/^\*\.//; s/^\*//' | sort -u
}

do_ipsets() {
    for s in direct_domains direct_domains_udp; do
        ipset create $s hash:ip timeout 86400 2>/dev/null || true
    done
    for s in direct_domains6 direct_domains6_udp; do
        ipset create $s hash:ip family inet6 timeout 86400 2>/dev/null || true
    done
    for s in direct_subnets direct_subnets_udp; do
        ipset create $s hash:net 2>/dev/null || true
    done
    for s in direct_subnets6 direct_subnets6_udp; do
        ipset create $s hash:net family inet6 2>/dev/null || true
    done
}

# All World domains (local + remote, same auto-update switch), one per line
world_domains() {
    {
        cat "$H/vpn-domains.txt" "$H/vpn-domains-udp.txt"
        auto_update_on && cat "$H/remote-lists/tcp_udp_domains.txt" "$H/remote-lists/udp_domains.txt"
    } 2>/dev/null | tr -d ' \t\r' | grep -v '^#' | grep -v '^$' | sed 's/^\*\.//; s/^\*//' | sort -u
}

# $1 local list, $2 remote list, $3 output conf, $4 IPv4 set, $5 IPv6 set.
# Only plain domains pass: one bad line would make dnsmasq reject the whole file.
# An entry listed in World as well (any letter case) is left out here: with two equal lines dnsmasq
# would pick one of them, and the agreed rule is that World (via VPN) wins.
gen_conf() {
    local tmp="$3.tmp.$$" world="/tmp/direct-lists-world.$$"
    world_domains > "$world"
    # never an empty pattern file (a comment line can not match a domain)
    [ -s "$world" ] || echo "#none" > "$world"
    {
        echo "# Generated by direct-lists.sh: Russia list set -> $4,$5"
        merged "$1" "$2" | grep -E '^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$' | grep -vxiF -f "$world" | sed "s|.*|ipset=/&/$4,$5|"
    } > "$tmp" && mv "$tmp" "$3"
    rm -f "$world"
}

do_dnsmasq() {
    do_ipsets
    mkdir -p /opt/etc/dnsmasq.d
    gen_conf "$DOM" "$R/tcp_udp_domains.txt" "$CONF" direct_domains direct_domains6
    gen_conf "$DOM_UDP" "$R/udp_domains.txt" "$CONF_UDP" direct_domains_udp direct_domains6_udp
    log "dnsmasq: $(grep -c '^ipset=' "$CONF") TCP+UDP, $(grep -c '^ipset=' "$CONF_UDP") UDP-only domains"
}

# $1 local list, $2 remote list, $3 IPv4 set, $4 IPv6 set
load_set() {
    local s
    for s in "$3" "$4"; do ipset destroy "${s}_tmp" 2>/dev/null; done
    ipset create "${3}_tmp" hash:net 2>/dev/null || return 1
    ipset create "${4}_tmp" hash:net family inet6 2>/dev/null || return 1
    merged "$1" "$2" | while read -r n; do
        case "$n" in
            *:*/*) ipset -exist add "${4}_tmp" "$n" 2>/dev/null ;;
            *.*/*) ipset -exist add "${3}_tmp" "$n" 2>/dev/null ;;
        esac
    done
    for s in "$3" "$4"; do
        ipset swap "${s}_tmp" "$s" 2>/dev/null
        ipset destroy "${s}_tmp" 2>/dev/null
    done
}

do_subnets() {
    do_ipsets
    load_set "$SUB" "$R/tcp_udp_subnets.txt" direct_subnets direct_subnets6
    load_set "$SUB_UDP" "$R/udp_subnets.txt" direct_subnets_udp direct_subnets6_udp
    log "subnets: $(ipset list direct_subnets 2>/dev/null | grep -c '^[0-9]') TCP+UDP, $(ipset list direct_subnets_udp 2>/dev/null | grep -c '^[0-9]') UDP-only (IPv4)"
}

do_download() {
    local src f tmp got=0
    src=$(jq -r '.lists_source_url // empty' "$SETTINGS_FILE" 2>/dev/null)
    [ -z "$src" ] && src="$DEFAULT_LISTS_SOURCE"
    mkdir -p "$R"
    for f in $REMOTE_FILES; do
        tmp="/tmp/direct-lists-$f"
        rm -f "$tmp"
        # Through the VPN first (the lists host may be blocked), then directly
        sing-box tools fetch -c /opt/etc/sing-box/config.json -o vpn "$src/direct_$f" > "$tmp" 2>/dev/null ||
            curl -sf --max-time 30 -o "$tmp" "$src/direct_$f" 2>/dev/null
        # A missing file comes back as a 404 page: keep the previous copy then
        if [ -s "$tmp" ] && ! grep -qiE '<html|^404: Not Found' "$tmp"; then
            mv "$tmp" "$R/$f"
            got=$((got + 1))
        else
            rm -f "$tmp"
        fi
    done
    log "download: $got of 4 direct_* files from $src (missing ones keep the previous copy)"
}

do_destroy() {
    for s in direct_domains direct_domains_udp direct_domains6 direct_domains6_udp \
             direct_subnets direct_subnets_udp direct_subnets6 direct_subnets6_udp; do
        ipset destroy $s 2>/dev/null || true
    done
}

case "$1" in
    ipsets)   do_ipsets ;;
    dnsmasq)  do_dnsmasq ;;
    subnets)  do_subnets ;;
    download) do_download ;;
    all)      do_ipsets; do_dnsmasq; do_subnets ;;
    destroy)  do_destroy ;;
    *)        echo "Usage: $0 {ipsets|dnsmasq|subnets|download|all|destroy}"; exit 1 ;;
esac
