#!/bin/sh
# =============================================================================
# DNS upstream fallback: plain UDP/TCP :53 → DoT via stubby (127.0.0.1:5453)
#
# dnsmasq listens on :5353 (client DNS + ipset). Upstream is either:
#   plain  — gateway + 8.8.8.8 / 1.1.1.1 (port 53)
#   dot    — stubby DoT stub on 127.0.0.1:5453 (when outbound :53 is blocked)
#
# Does NOT use ndnproxy :53 — keeps system DNS independent (see auto-install-guide).
# =============================================================================

export PATH="/opt/bin:/opt/sbin:/opt/usr/bin:/bin:/sbin:/usr/bin:/usr/sbin:$PATH"

VPN_MANAGER_HOME="${VPN_MANAGER_HOME:-/opt/etc/vpn-manager}"
DNS_UPSTREAM_CONF="/opt/etc/dnsmasq.d/00-upstream-dns.conf"
MODE_FILE="$VPN_MANAGER_HOME/dns-upstream-mode"
STUBBY_CONF="$VPN_MANAGER_HOME/stubby.yml"
STUBBY_PORT=5453
STUBBY_INIT="/opt/etc/init.d/S55dns-dot-stub"
DNSMASQ_INIT="/opt/etc/init.d/S56dnsmasq"

log_info() { printf '[dns-upstream] %s\n' "$1"; }
log_ok()   { printf '[dns-upstream] OK: %s\n' "$1"; }
log_warn() { printf '[dns-upstream] WARN: %s\n' "$1"; }

get_dnsmasq_port() {
    local port=5353
    if command -v jq >/dev/null 2>&1 && [ -f "$VPN_MANAGER_HOME/settings.json" ]; then
        port=$(jq -r '.dnsmasq_port // 5353' "$VPN_MANAGER_HOME/settings.json" 2>/dev/null)
    fi
    if [ -f "$DNS_UPSTREAM_CONF" ]; then
        local p
        p=$(grep '^port=' "$DNS_UPSTREAM_CONF" 2>/dev/null | head -1 | cut -d= -f2)
        [ -n "$p" ] && port="$p"
    fi
    echo "$port"
}

get_default_gateway() {
    local gateway
    gateway=$(ip route 2>/dev/null | grep 'default via' | awk '{print $3}' | head -1)
    if [ -n "$gateway" ] && echo "$gateway" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
        echo "$gateway"
    fi
}

ensure_dig() {
    command -v dig >/dev/null 2>&1 && return 0
    opkg update >/dev/null 2>&1 || true
    opkg install bind-dig >/dev/null 2>&1 || true
    command -v dig >/dev/null 2>&1
}

test_plain_dns() {
    ensure_dig || return 1
    dig @8.8.8.8 google.com +short +time=2 >/dev/null 2>&1
}

test_dot_dns() {
    ensure_dig || return 1
    dig @8.8.8.8 google.com +tls +short +time=3 >/dev/null 2>&1
}

test_dnsmasq_local() {
    local port="$1"
    ensure_dig || return 1
    dig @127.0.0.1 -p "$port" google.com +short +time=2 >/dev/null 2>&1
}

test_stubby_local() {
    ensure_dig || return 1
    dig @127.0.0.1 -p "$STUBBY_PORT" google.com +short +time=2 >/dev/null 2>&1
}

write_plain_upstream() {
    local port="$1"
    local gateway="$2"

    cat > "$DNS_UPSTREAM_CONF" << EOF
# dnsmasq configuration for VPN Manager
# Generated by dns-upstream-fallback.sh
# upstream-mode: plain

# Listen on port $port (clients redirected from :53 via iptables)
port=$port

no-resolv

# Upstream DNS — UDP/TCP port 53
EOF

    if [ -n "$gateway" ]; then
        cat >> "$DNS_UPSTREAM_CONF" << EOF
# Primary — default gateway
server=$gateway

EOF
    fi

    cat >> "$DNS_UPSTREAM_CONF" << 'EOF'
server=8.8.8.8
server=1.1.1.1
server=8.8.4.4
EOF
}

write_dot_upstream() {
    local port="$1"

    cat > "$DNS_UPSTREAM_CONF" << EOF
# dnsmasq configuration for VPN Manager
# Generated by dns-upstream-fallback.sh
# upstream-mode: dot

# Listen on port $port (clients redirected from :53 via iptables)
port=$port

no-resolv

# DoT stub (stubby) — used when outbound port 53 is blocked on WAN
server=127.0.0.1#$STUBBY_PORT
EOF
}

write_stubby_config() {
    mkdir -p "$VPN_MANAGER_HOME" /opt/var/lib/stubby
    cat > "$STUBBY_CONF" << 'EOF'
# DoT stub for dnsmasq upstream (VPN Manager)
resolution_type: GETDNS_RESOLUTION_STUB
# Round-robin makes stubby renegotiate TLS with a different upstream on nearly
# every query; on this hardware the handshake regularly outran the client
# timeout and roughly a third of answers came back empty. Sticking to one
# upstream keeps the connection alive and still fails over when it breaks.
round_robin_upstreams: 0
idle_timeout: 60000
appdata_dir: "/opt/var/lib/stubby"
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
# Without an explicit bundle every upstream fails verification with
# "self-signed certificate in certificate chain": the firmware ships individual
# certs in /etc/ssl/certs but no concatenated bundle, so getdns finds no trust
# anchors. The bundle comes from the ca-bundle package, which we already install.
tls_ca_file: "/opt/etc/ssl/certs/ca-certificates.crt"
listen_addresses:
  - 127.0.0.1@5453
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
upstream_recursive_servers:
  - address_data: 8.8.8.8
    tls_auth_name: "dns.google"
  - address_data: 8.8.4.4
    tls_auth_name: "dns.google"
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"
EOF
}

install_stubby() {
    # Require the Entware build, not the firmware one: Keenetic ships stubby 0.4.0
    # in /usr/sbin, which rejects tls_ca_file and so cannot do strict TLS auth at
    # all (every upstream fails with "self-signed certificate in certificate chain").
    # ca-certificates supplies the hashed trust store the verification needs.
    [ -x /opt/sbin/stubby ] && return 0
    log_info "Installing stubby (DoT stub) from Entware..."
    opkg update >/dev/null 2>&1 || true
    opkg install stubby ca-certificates >/dev/null 2>&1 || return 1
    [ -x /opt/sbin/stubby ]
}

start_stubby() {
    stop_stubby
    if [ -x "$STUBBY_INIT" ]; then
        "$STUBBY_INIT" start 2>&1
    else
        stubby -C "$STUBBY_CONF" -g >/dev/null 2>&1 &
    fi
    sleep 2
    test_stubby_local
}

stop_stubby() {
    # dns-dot-domains.sh points individual VPN-list domains at the stub even while
    # the general upstream stays plain, so the stub is still in use here. Without
    # this guard the 15-minute plain-mode run would kill it and break every one of
    # those domains until the next 10-minute sync restarted it.
    if [ -f "/opt/etc/dnsmasq.d/vpn-domains-dot.conf" ]; then
        return 0
    fi

    if [ -x "$STUBBY_INIT" ]; then
        "$STUBBY_INIT" stop >/dev/null 2>&1 || true
    else
        killall stubby 2>/dev/null || true
    fi
}

restart_dnsmasq() {
    [ -x "$DNSMASQ_INIT" ] && "$DNSMASQ_INIT" restart >/dev/null 2>&1 || true
}

apply_plain_mode() {
    local port="$1"
    local gateway="$2"
    local do_restart="$3"

    write_plain_upstream "$port" "$gateway"
    echo "plain" > "$MODE_FILE"
    stop_stubby
    log_ok "upstream: plain (gateway=${gateway:-none}, 8.8.8.8, 1.1.1.1)"

    if [ "$do_restart" = "1" ]; then
        restart_dnsmasq
        sleep 2
    fi
    return 0
}

apply_dot_mode() {
    local port="$1"
    local do_restart="$2"

    install_stubby || {
        log_warn "stubby not available, cannot enable DoT fallback"
        return 1
    }

    write_stubby_config
    start_stubby || {
        log_warn "stubby failed to start or respond on 127.0.0.1:$STUBBY_PORT"
        return 1
    }

    write_dot_upstream "$port"
    echo "dot" > "$MODE_FILE"
    log_ok "upstream: DoT via stubby (127.0.0.1:$STUBBY_PORT → tls://8.8.8.8 / 1.1.1.1)"

    if [ "$do_restart" = "1" ]; then
        restart_dnsmasq
        sleep 2
    fi

    if test_dnsmasq_local "$port"; then
        log_ok "dnsmasq responds on 127.0.0.1:$port"
        return 0
    fi

    log_warn "dnsmasq still not responding on 127.0.0.1:$port after DoT switch"
    return 1
}

# Detect best upstream and apply. Switches plain↔dot when WAN conditions change.
apply_dns_upstream() {
    local do_restart=1
    local quiet=0

    while [ $# -gt 0 ]; do
        case "$1" in
            --no-restart) do_restart=0 ;;
            --quiet) quiet=1 ;;
        esac
        shift
    done

    local port gateway current_mode new_mode
    port=$(get_dnsmasq_port)
    gateway=$(get_default_gateway)
    current_mode=""
    [ -f "$MODE_FILE" ] && current_mode=$(cat "$MODE_FILE" 2>/dev/null)

    if test_plain_dns; then
        new_mode="plain"
        if [ "$current_mode" = "plain" ] && [ -f "$DNS_UPSTREAM_CONF" ]; then
            [ "$quiet" = "0" ] && log_ok "upstream unchanged: plain"
            return 0
        fi
        [ "$quiet" = "0" ] && log_info "outbound DNS port 53 OK — using plain upstream"
        apply_plain_mode "$port" "$gateway" "$do_restart"
        return $?
    fi

    if test_dot_dns; then
        new_mode="dot"
        if [ "$current_mode" = "dot" ] && test_dnsmasq_local "$port"; then
            [ "$quiet" = "0" ] && log_ok "upstream unchanged: dot (dnsmasq OK)"
            return 0
        fi
        [ "$quiet" = "0" ] && log_info "outbound DNS port 53 blocked — switching to DoT (stubby)"
        apply_dot_mode "$port" "$do_restart"
        return $?
    fi

    log_warn "no working DNS upstream (plain :53 and DoT both failed)"
    return 1
}

cmd_status() {
    local port mode
    port=$(get_dnsmasq_port)
    mode="unknown"
    [ -f "$MODE_FILE" ] && mode=$(cat "$MODE_FILE" 2>/dev/null)

    echo "mode: $mode"
    echo "dnsmasq_port: $port"
    echo "plain_dns: $(test_plain_dns && echo OK || echo FAIL)"
    echo "dot_dns: $(test_dot_dns && echo OK || echo FAIL)"
    echo "dnsmasq_local: $(test_dnsmasq_local "$port" && echo OK || echo FAIL)"
    echo "stubby_local: $(test_stubby_local && echo OK || echo FAIL)"
    if [ -f "$DNS_UPSTREAM_CONF" ]; then
        echo "upstream_servers:"
        grep '^server=' "$DNS_UPSTREAM_CONF" 2>/dev/null
    fi
}

case "${1:-apply}" in
    apply)
        shift
        apply_dns_upstream "$@"
        ;;
    status)  cmd_status ;;
    test)
        test_plain_dns && echo "plain: OK" || echo "plain: FAIL"
        test_dot_dns && echo "dot: OK" || echo "dot: FAIL"
        ;;
    *)
        echo "Usage: $0 {apply|status|test} [--no-restart] [--quiet]"
        exit 1
        ;;
esac
