#!/bin/sh
# =============================================================================
# Route VPN-list domains through the local DoT stub (stubby, 127.0.0.1:5453).
#
# Why: some providers do not block port 53, they forge answers for specific
# names (observed: NXDOMAIN with the aa flag, 4 ms round-trip). dnsmasq cannot
# detect that — a forged reply is a valid reply — so there is nothing to fall
# back from. The only fix is to deny the provider the chance to lie: resolve
# those names over TLS, where it sees neither the question nor the answer.
#
# Scope: only domains already listed in the generated ipset= configs, i.e.
# exactly the domains routed via VPN. Everything else keeps the normal upstream.
#
# Also acts as a stubby watchdog: if the stub is down the generated config is
# removed, so those domains fall back to the normal upstream instead of failing.
# =============================================================================

export PATH="/opt/bin:/opt/sbin:/opt/usr/bin:/bin:/sbin:/usr/bin:/usr/sbin:$PATH"

STUBBY_PORT=5453
STUBBY_INIT="/opt/etc/init.d/S55dns-dot-stub"
DNSMASQ_INIT="/opt/etc/init.d/S56dnsmasq"
SRC_TCPUDP="/opt/etc/dnsmasq.d/vpn-domains.conf"
SRC_UDP="/opt/etc/dnsmasq.d/vpn-domains-udp.conf"
OUT="/opt/etc/dnsmasq.d/vpn-domains-dot.conf"
TMP="/tmp/vpn-domains-dot.$$"

log() { printf '[dns-dot] %s\n' "$1"; }

cleanup() { rm -f "$TMP"; }
trap cleanup EXIT

stubby_alive() {
    command -v dig >/dev/null 2>&1 || return 1
    dig @127.0.0.1 -p "$STUBBY_PORT" google.com +short +time=2 +tries=1 2>/dev/null \
        | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'
}

# Watchdog: bring the stub back if it died, then re-check.
ensure_stubby() {
    stubby_alive && return 0
    [ -x "$STUBBY_INIT" ] || { log "stub init script missing: $STUBBY_INIT"; return 1; }
    log "stub not responding on 127.0.0.1:$STUBBY_PORT — restarting"
    "$STUBBY_INIT" restart >/dev/null 2>&1
    sleep 3
    stubby_alive
}

drop_config() {
    [ -f "$OUT" ] || return 0
    rm -f "$OUT"
    log "removed $OUT — domains revert to the normal upstream"
    [ -x "$DNSMASQ_INIT" ] && "$DNSMASQ_INIT" restart >/dev/null 2>&1
}

if ! ensure_stubby; then
    log "DoT stub unavailable"
    drop_config
    exit 1
fi

{
    echo "# Automatically generated by dns-dot-domains.sh — do not edit."
    echo "# VPN-list domains are resolved over TLS via stubby on 127.0.0.1:$STUBBY_PORT,"
    echo "# so the provider cannot forge answers for them."
    echo
    cat "$SRC_TCPUDP" "$SRC_UDP" 2>/dev/null \
        | sed -n 's|^ipset=/\([^/]*\)/.*|\1|p' \
        | sed 's/[[:space:]]//g' \
        | grep -v '^$' \
        | sort -u \
        | while read -r domain; do
            echo "server=/$domain/127.0.0.1#$STUBBY_PORT"
        done
} > "$TMP"

count=$(grep -c '^server=' "$TMP" 2>/dev/null || echo 0)

if [ "$count" = "0" ]; then
    log "no domains in the generated ipset configs — nothing to route"
    drop_config
    exit 0
fi

# Restart dnsmasq only when the result actually changed, so the cron run stays quiet.
if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
    log "unchanged ($count domains)"
    exit 0
fi

cat "$TMP" > "$OUT"
log "updated: $count domains via DoT"
[ -x "$DNSMASQ_INIT" ] && "$DNSMASQ_INIT" restart >/dev/null 2>&1
log "dnsmasq restarted"
exit 0
